# A test map for car parking

[scene]
name = "Parking Lot"
west = 0.0
east = 6.0
south = 0.0
north = 10.0

resolution = 0.1

obstacles = [
    { west = 0.0, east = 1.4, south = 0.0, north = 3.8 },
    { west = 0.0, east = 1.4, south = 7.0, north = 10.0}
]
slot = { length = 2.8, width = 1.4, position = [0.0, 4.2], orientation = 90 }

[vehicle]
length = 2
width = 1
wheelbase = 1.4
front_to_base_axle = 1.6
max_steering_angle = 35.0

[planner]
start_pose = [4.0, 5.0, 0.0]
goal_pose = [0.7, 5.2, 90.0]
angle_resolution = 120
reverse_penalty = 1.5
error_goal_meter = 0.2
error_goal_degree = 1.5

[astar]
heuristic_weight = 1.0
step_length = 0.2

[result]
save = true
path = "../../resources/parking-lot-4.png"
